In [1]:
import pandas as pd

In [2]:
# Working with JSON

In [3]:
pd.read_json('./Dataset/train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [6]:
pd.read_json("URL")

In [ ]:
# Working with SQL

In [8]:
!pip install mysql.connector

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql.connector in c:\users\anshu\appdata\roaming\python\python312\site-packages (2.2.9)

In [10]:
import mysql.connector

In [18]:
conn = mysql.connector.connect(host = 'localhost', user = 'root', password = '', database = 'world')

In [28]:
pd.read_sql_query("SELECT * FROM city WHERE Population > 170000", conn)

C:\Users\anshu\AppData\Local\Temp\ipykernel_22968\983424863.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE Population > 170000", conn)

        ID         Name CountryCode       District  Population
0        1        Kabul         AFG          Kabol     1780000
1        2     Qandahar         AFG       Qandahar      237500
2        3        Herat         AFG          Herat      186800
3        5    Amsterdam         NLD  Noord-Holland      731200
4        6    Rotterdam         NLD   Zuid-Holland      593321
...    ...          ...         ...            ...         ...
2002  3915       Oxnard         USA     California      170358
2003  4068       Harare         ZWE         Harare     1410000
2004  4069     Bulawayo         ZWE       Bulawayo      621742
2005  4070  Chitungwiza         ZWE         Harare      274912
2006  4074         Gaza         PSE           Gaza      353632

[2007 rows x 5 columns]

In [22]:
pd.read_sql_query("SELECT * FROM country WHERE LifeExpectancy > 60", conn)

C:\Users\anshu\AppData\Local\Temp\ipykernel_22968\4278207049.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM country WHERE LifeExpectancy > 60", conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129,AW
1,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62,AI
2,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34,AL
3,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,,55,AD
4,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33,AN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,VIR,"Virgin Islands, U.S.",North America,Caribbean,347.0,NaN,93000,78.1,0.0,NaN,Virgin Islands of the United States,US Territory,George W. Bush,4067,VI
163,VNM,Vietnam,Asia,Southeast Asia,331689.0,1945.0,79832000,69.3,21929.0,22834.0,Viêt Nam,Socialistic Republic,Trân Duc Luong,3770,VN
164,VUT,Vanuatu,Oceania,Melanesia,12189.0,1980.0,190000,60.6,261.0,246.0,Vanuatu,Republic,John Bani,3537,VU
165,WSM,Samoa,Oceania,Polynesia,2831.0,1962.0,180000,69.2,141.0,157.0,Samoa,Parlementary Monarchy,Malietoa Tanumafili II,3169,WS
166,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792,YU

In [30]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'NLD'", conn)

C:\Users\anshu\AppData\Local\Temp\ipykernel_22968\3395324654.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'NLD'", conn)

    ID              Name CountryCode       District  Population
0    5         Amsterdam         NLD  Noord-Holland      731200
1    6         Rotterdam         NLD   Zuid-Holland      593321
2    7              Haag         NLD   Zuid-Holland      440900
3    8           Utrecht         NLD        Utrecht      234323
4    9         Eindhoven         NLD  Noord-Brabant      201843
5   10           Tilburg         NLD  Noord-Brabant      193238
6   11         Groningen         NLD      Groningen      172701
7   12             Breda         NLD  Noord-Brabant      160398
8   13         Apeldoorn         NLD     Gelderland      153491
9   14          Nijmegen         NLD     Gelderland      152463
10  15          Enschede         NLD     Overijssel      149544
11  16           Haarlem         NLD  Noord-Holland      148772
12  17            Almere         NLD      Flevoland      142465
13  18            Arnhem         NLD     Gelderland      138020
14  19          Zaanstad         NLD  Noord-Holland      135621
15  20  ´s-Hertogenbosch         NLD  Noord-Brabant      129170
16  21        Amersfoort         NLD        Utrecht      126270
17  22        Maastricht         NLD        Limburg      122087
18  23         Dordrecht         NLD   Zuid-Holland      119811
19  24            Leiden         NLD   Zuid-Holland      117196
20  25    Haarlemmermeer         NLD  Noord-Holland      110722
21  26        Zoetermeer         NLD   Zuid-Holland      110214
22  27             Emmen         NLD        Drenthe      105853
23  28            Zwolle         NLD     Overijssel      105819
24  29               Ede         NLD     Gelderland      101574
25  30             Delft         NLD   Zuid-Holland       95268
26  31           Heerlen         NLD        Limburg       95052
27  32           Alkmaar         NLD  Noord-Holland       92713